create database KUTV;

-- USE KUTV

CREATE TABLE Iskola (
	IskolaID INT AUTO_INCREMENT PRIMARY KEY,
    IskolaNev varchar(255) NOT NULL 
);

INSERT INTO Iskola (IskolaNev)
values('János Zsigmond Unitárius Kollégium'),
	('Székely Mikó Kollégium'),
    ('Bolyai Farkas Elméleti Líceum'),
    ('Silvania Főgimnázium'),
    ('Andrei Mureșanu Főgimnázium'),
    ('Márton Áron Főgimnázium'),
    ('Mikes Kelemen Elméleti Líceum'),
    ('Apáczai Csere János Elméleti Líceum'),
    ('Kolozsvári Református Kollégium'),
    ('Segítő Mária Római Katolikus Teológiai Líceum'),
    ('Benedek Elek Pedagógiai Líceum'),
    ('Marosvásárhelyi Református Kollégium'),
    ('Bethlen Gábor Kollégium'),
    ('Salamon Ernő Gimnázium'),
    ('Hám János Római Katolikus Teológiai Líceum'),
    ('Baczkamadarasi Kis Gergely Református Kollégium'),
    ('II. Rákóczi Ferenc Római Katolikus Teológiai Líceum'),
    ('Sigismund Toduță Zenei Főgimnázium'),
    ('Tamási Áron Gimnázium'),
    ('Nagykárolyi Elméleti Líceum'),
    ('Mihai Eminescu Főgimnázium'),
    ('Kölcsey Ferenc Főgimnázium'),
    ('Báthory István Elméleti Líceum'),
    ('Simion Bărnuțiu Főgimnázium'),
    ('Áprily Lajos Főgimnázium'),
    ('Református Teológiai Líceum'),
    ('Kézdivásárhelyi Református Kollégium'),
    ('Jósika Miklós Elméleti Líceum'),
    ('Bartók Béla Elméleti Líceum'),
    ('Lucian Blaga Technológiai Líceum'),
    ('Petru Maior Technológiai Líceum'),
    ('Octavian Goga Elméleti Líceum'),
    ('Németh László Elméleti Líceum'),
    ('Onisifor Ghibu Elméleti Líceum'),
    ('Mihai Eminescu Pedagógiai Főgimnázium'),
    ('Művészeti Szaklíceum'),
    ('Csiky Gergely Főgimnázium'),
    ('Joannes Kájoni Szakközépiskola'),
    ('Kőrösi Csoma Sándor Líceum'),
    ('Ady Endre Elméleti Líceum'),
    ('Nagy Mózes Elméleti Líceum'),
    ('Bod Péter Tanítóképző'),
    ('Kemény Zsigmond Elméleti Líceum'),
    ('Plugor Sándor Művészeti Líceum'),
    ('Gheorghe Șincai Tanítóképző'),
    ('Ady Endre Elméleti Líceum'),
    ('Kemény János Elméleti Líceum'),
    ('Iosif Vulcan Főgimnázium'),
    ('Domokos Kázmér Óvoda, Gimnázium és Szakközépiskola'),
    ('Nagyváradi Művészeti Líceum'),
    ('Nagy István Művészeti Középiskola'),
    ('Elektromaros Technológiai Líceum'),
    ('Dr. Palló Imre Művészeti Líceum'),
    ('Téglás Gábor Elméleti Líceum'),
    ('Kós Károly Szakközépiskola'),
    ('Zilahi Református Wesselényi Kollégium'),
    ('Andrei Bârseanu Elméleti Líceum'),
    ('Arany János Elméleti Líceum'),
    ('Brassai Sámuel Elméleti Líceum'),
    ('Nemzeti Gázipari Iskola'),
    ('Orbán Balázs Elméleti Líceum'),
    ('Cserey–Goga Technológiai Líceum'),
    ('Tasnádi Technológiai Líceum'),
    ('Berde Áron Kereskedelmi és Közigazgatási Szakközépiskola'),
    ('Lorántffy Zsuzsanna Református Gimnázium'),
    ('Szatmárnémeti Református Líceum'),
    ('Petőfi Sándor Iskolaközpont'),
    ('Petőfi Sándor Elméleti Líceum'),
    ('Berde Mózes Unitárius Gimnázium'),
    ('Aurel Popp Képzőművészeti Líceum'),
    ('Mircea Eliade Főgimnázium'),
    ('Baróti Szabó Dávid Technológiai Líceum'),
    ('Szász Adalbert Sportlíceum'),
    ('Zajzoni Rab István Középiskola'),
    ('Bocskai István Elméleti Líceum'),
    ('Szent László Római Katolikus Teológiai Líceum'),
    ('Gróf Majláth Gusztáv Károly Római Katolikus Teológiai Líceum'),
    ('Gheorghe Pop de Băseşti Technológiai Líceum'),
    ('Horváth János Elméleti Líceum'),
    ('Josephus Calasantius Római Katolikus Líceum'),
    ('Szent György Technológiai Líceum'),
    ('Érmihályfavi 1-es Számú Mezőgazdasági Líceum'),
    ('Leőwey Klára Elméleti Líceum'),
    ('Marosludasi 1-es Számú Technológiai Líceum'),
    ('Szent Erzsébet Római Katolikus Líceum'),
    ('Kós Károly Szakközépiskola'),
    ('Római Katolikus Gerhardinum Teológiai Líceum'),
    ('Venczel József Szakközépiskola');
    
    
 